### ISSUE TITLE
Can you kindly provide database_json examples?

### ISSUE THREAD

**Issue by liutaocode** [fgnt/graph_pit#8]
Hello,
Thanks for your wonderfull job.

I am not familar with database_json format. Can you provide an example for us? So we can reproduce the result.

Thanks.

**Comment by liutaocode** [comment]
From my understanding, we need to generate train_si284.json dev93.json and test92.json data from kaldi wsj recepie first. Is that right?

**Comment by thequilo** [comment]
Hi @liutaocode!

I can, unfortunately, not provide the full `database_json` for the WSJ database due to WSJ's license. We have, however, published a meeting mixture generator called MMS-MSG (https://github.com/fgnt/mms_msg) that can create a file similar to what you need to run the example. The JSON format changed slightly, you would need to rename a few keys:
 - `audio_path.original_source` -> `audio_path.speech_source` 
 - `num_samples.original_source` -> `num_samples.speech_source`
 - `offset.original_source` -> `offset`
and add the keys `speech_onset` (=`offset.original_source`) and `speech_offset` (=`offset.original_source + num_samples.original_source`)

As a reference, this is the expected JSON format:

```python
{
  "datasets": {
    "<dataset_name>": {
      "<example_id>": {
	"audio_path": {
          "speech_source": [
            "/absolute/path/to/wav/file.wav",
            # ... (One file for each utterance)
          ],
          "rirs": [...] # Absolute paths to RIRs for reverberant data
        },
        "example_id": "<unique ID>",
        "log_weights": [
	  0.42,
	  # ... One for each utterance. Logarithmic weighting factor
        ],
        "num_samples": {
	   "observation": 123456,   # Number of samples of the generated audio
           "speech_source": [
	     123,
             # ... Number of samples for each file in "audio_path.speech_source"
          ]
        },
        "offset": [
          13498,
          # ... Starting point in samples for each utterance
        ],
        "speaker_id": [
          "4k2",
	      # ... Speaker ID for each utterance
        ],
        "speech_offset": [
          69138,
          # ... End point of speech in samples, for each utterance. Can be equal to offset
        ],
        "speech_onset": [
          22378,
          # ... Start point of speech in samples, for each utterance. Can be equal to offset + num_samples.speech_source
        ],
      }
    }
  }
}
```

Anyways, thanks for bringing this up. It's a good idea to adjust the example to use mms_msg so that it's easier to use.

**Comment by liutaocode** [comment]
Thanks for your clear explaination~ I made it by following your example.
